<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="lidar_stick_joint" type="fixed">
        <parent link="robot_link"/>
        <child link="lidar_stick_link"/>
        <origin xyz="${robot_size_x / 2.0} 0.0 ${robot_size_z + 0.05}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="lidar_stick_link">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="0.1"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="0.1"/>
            </geometry>
            <material name="green"/>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="0.01" h="0.1"/>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="lidar_stick_link"/>
        <child link="laser_frame"/>
        <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.035" length="0.02"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.035" length="0.02"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <xacro:cylinder_inertia m="0.2" r="0.035" h="0.02"/>
    </link>

    <gazebo reference="laser_frame">
        <sensor name='lidar' type='gpu_lidar'>
            <pose>0 0 0 0 0 0</pose>
            <topic>scan</topic>
            <update_rate>10</update_rate>  <!-- Reducido de 20 a 10Hz para mejor sincronizaci칩n -->
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>4.0</max>
                    <resolution>0.01</resolution>  <!-- A침adida resoluci칩n para mejor precisi칩n -->
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>  <!-- Ruido realista pero bajo -->
                </noise>
            </lidar>
            <gz_frame_id>laser_frame</gz_frame_id>
            <always_on>1</always_on>
            <visualize>false</visualize>
        </sensor>
    </gazebo>
    
</robot>