<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="lidar_stick_joint" type="fixed">
        <parent link="robot_link"/>
        <child link="lidar_stick_link"/>
        <origin xyz="${robot_size_x / 2.0} 0.0 ${robot_size_z + 0.05}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="lidar_stick_link">
        <visual>
            <geometry>
                <cylinder radius="0.02" length="0.1"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.02" length="0.2"/>
            </geometry>
            <material name="green"/>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="0.02" h="0.2"/>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="lidar_stick_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="0.07" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.07" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <xacro:cylinder_inertia m="0.2" r="0.07" h="0.04"/>
    </link>
    
</robot>