<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="materials.xacro" />
    <xacro:include filename="constants.xacro" />
    <xacro:include filename="inertial_properties.xacro" />

    <!-- BASE LINK -->

    <link name="base_link">
        
    </link>

    <!-- BASE FOOTPRINT LINK AND JOINT -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="base_footprint"></link>

    <!-- ROBOT JOINT (BASE LINK - ROBOT'S FRAME) -->

    <joint name="robot_joint" type="fixed">
        <parent link="base_link"/>
        <child link="robot_link"/>
        <origin xyz="${-radius_wheel} 0.0  0.0"/>
    </joint>

    <!-- ROBOT LINK (ROBOT'S FRAME) -->

    <link name="robot_link">
        <visual>
            <origin xyz="${robot_size_x / 2} 0.0 ${robot_size_z / 2}"/>
            <geometry>
                <box size="${robot_size_x} ${robot_size_y} ${robot_size_z}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="${robot_size_x / 2} 0.0 ${robot_size_z / 2}"/>
            <geometry>
                <box size="${robot_size_x} ${robot_size_y} ${robot_size_z}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="2.0" w="${robot_size_x}" d="${robot_size_y}" h="${robot_size_z}"/>
    </link>

    <!-- LEFT WHEEL JOINT-->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.0 ${robot_size_y / 2 + height_wheel / 2} ${radius_wheel - idler_wheel_radius}" rpy="${-pi / 2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <!-- LEFT WHEEL LINK -->

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${radius_wheel}" length="${height_wheel}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${radius_wheel}" length="${height_wheel}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${radius_wheel}" h="${height_wheel}"/>
    </link>

    <!-- RIGHT WHEEL JOINT-->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.0 ${-robot_size_y / 2 - height_wheel / 2} ${radius_wheel - idler_wheel_radius}" rpy="${-pi / 2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <!-- RIGHT WHEEL LINK -->

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${radius_wheel}" length="${height_wheel}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${radius_wheel}" length="${height_wheel}"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${radius_wheel}" h="${height_wheel}"/>
    </link>

    <!-- IDLER WHEEL JOINT -->

    <joint name="idler_wheel_joint" type="fixed">
        <parent link="robot_link"/>
        <child link="idler_wheel_link"/>
        <origin xyz="${robot_size_x - 0.05} 0.0 0.0"/>
    </joint>

    <!-- IDLER WHEEL LINK -->

    <link name="idler_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${idler_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${idler_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:sphere_inertia m="0.05" r="${idler_wheel_radius}"/>
    </link>

    <gazebo reference="idler_wheel_link">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>