# https://github.com/ros-controls/ros2_control_demos/blob/master/example_2/bringup/config/diffbot_controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 50  # Hz - Aumentado para mejor respuesta
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.35  # Corregido según geometría real
    wheel_radius: 0.10

    use_stamped_vel: false  # Simplificado

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false  # Usar retroalimentación para mejor control
    enable_odom_tf: true

    cmd_vel_timeout: 1.0  # Más tiempo antes de parar
    publish_limited_velocity: false  # Deshabilitar limitación
    velocity_rolling_window_size: 1  # Sin filtrado, respuesta inmediata

    # Límites de velocidad y aceleración más permisivos para respuesta inmediata
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: false  # Sin límites de aceleración
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: false  # Sin límites de aceleración
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0